# Platform
TARGET_BOARD_PLATFORM := clovertrail
# Architecture
TARGET_ARCH := x86
#TARGET_ARCH_VARIANT := x86-atom
TARGET_ARCH_VARIANT := x86
TARGET_CPU_ABI := x86
TARGET_CPU_ABI2 := armeabi-v7a
TARGET_CPU_SMP := true
TARGET_CPU_VARIANT := x86
# Bootloader
TARGET_NO_BOOTLOADER := true
TARGET_BOOTLOADER_BOARD_NAME := clovertrail
# Kernel
TARGET_PREBUILT_RECOVERY_KERNEL := device/a502cg/kernel
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048
cmdline_extra := watchdog.watchdog_thresh=60 androidboot.spid=xxxx:xxxx:xxxx:xxxx:xxxx:xxxx androidboot.serialno=01234567890123456789012345678901
BOARD_KERNEL_CMDLINE := init=/init pci=noearly console=logk0 earlyprintk=nologger loglevel=0 kmemleak=off androidboot.bootmedia=sdcard androidboot.hardware=redhookbay $(cmdline_extra) ip=50.0.0.2:50.0.0.1::255.255.255.0::usb0:on vmalloc=172M
# Partitions
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 1887436800
BOARD_CACHEIMAGE_PARTITION_SIZE := 536870912
BOARD_USERDATAIMAGE_PARTITION_SIZE := 4915703808
BOARD_FLASH_BLOCK_SIZE := 131072
# Recovery
TARGET_RECOVERY_PIXEL_FORMAT := "BGRA_8888"
TARGET_USERIMAGES_USE_EXT4 := true
BOARD_HAS_LARGE_FILESYSTEM := true
BOARD_USE_CUSTOM_RECOVERY_FONT := \"roboto_15x24.h\"
BOARD_SUPPRESS_EMMC_WIPE := true
# TWRP
HAVE_SELINUX := true
DEVICE_RESOLUTION := 540x960
TW_INCLUDE_INJECTTWRP := true
TWRP_EVENT_LOGGING := false
RECOVERY_SDCARD_ON_DATA := true
TARGET_RECOVERY_INITRC := device/a502cg/ramdisk/init.rc
TW_INTERNAL_STORAGE_PATH := "/mnt/sdcard"
TW_INTERNAL_STORAGE_MOUNT_POINT := "mnt"
TW_EXTERNAL_STORAGE_PATH := "/sdcard"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "sdcard"



